// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imbhghwnmslittqqklia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltYmhnaHdubXNsaXR0cXFrbGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzkwODksImV4cCI6MjA2NjI1NTA4OX0.p2HX0e6o7KJhOhpJKDbLmCvQ08xXzHMqi2KcDfYHF-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);